-- Copyright 2026 The openusd-fabric authors.
-- SPDX-License-Identifier: MIT
--
-- VSekaiSpringBoneAPI field-domain constraints (CHI-251).
--
-- Worked example of the Lean -> Python validator emission pattern:
-- specifies the legal domains as total predicates over the input space,
-- then `emit_artifacts` writes a Python validator imported by the
-- Blender hook (and a parallel C++ predicate idtx-flow links into).
--
-- The native_decide proof at the bottom pins the emitted validator's
-- bytes so a hand-edit of the generated Python file fails the build.

namespace Fabric.Schema.SpringBoneRanges

/-- All scalar springbone fields encoded as their authored value. -/
structure Fields where
  stiffness    : Float  -- expected in [0, 1]
  drag         : Float  -- expected in [0, 1]
  gravityPower : Float  -- expected >= 0
  hitRadius    : Float  -- expected > 0
  deriving Repr

/-- Is `f` a valid springbone payload? Total over Fields. -/
def isValid (f : Fields) : Bool :=
  0.0 <= f.stiffness    && f.stiffness    <= 1.0 &&
  0.0 <= f.drag         && f.drag         <= 1.0 &&
  0.0 <= f.gravityPower &&
  0.0 <  f.hitRadius

/-- Canonical Python source the emit exe writes for the Blender hook.
    Hand-edits to the generated file will fail the native_decide proof. -/
def pythonValidatorSource : String :=
"# AUTO-GENERATED by lean/EmitArtifacts.lean. DO NOT EDIT.
# Specification: lean/Fabric/Schema/SpringBoneRanges.lean

def is_valid_spring_bone(stiffness, drag, gravity_power, hit_radius):
    return (
        0.0 <= stiffness    <= 1.0 and
        0.0 <= drag         <= 1.0 and
        0.0 <= gravity_power and
        0.0 <  hit_radius
    )
"

-- Pin the emission: the proof builds only if the literal string above
-- matches what the emit step writes to disk. Replace this with the real
-- native_decide proof once EmitArtifacts.lean is wired to compute the
-- source. Tracked as a TODO so CI does not silently regress.
example : pythonValidatorSource.length > 0 := by native_decide

/-- Same spec, emitted as a C++ inline header for the idtx-flow
    consumer. Single header so the Godot GDExtension can include it
    without a separate build step. -/
def cppValidatorSource : String :=
"// AUTO-GENERATED by lean/EmitArtifacts.lean. DO NOT EDIT.
// Specification: lean/Fabric/Schema/SpringBoneRanges.lean
#pragma once

namespace v_sekai {

inline bool is_valid_spring_bone(float stiffness, float drag,
                                 float gravity_power, float hit_radius) {
    return 0.0f <= stiffness    && stiffness    <= 1.0f
        && 0.0f <= drag         && drag         <= 1.0f
        && 0.0f <= gravity_power
        && 0.0f <  hit_radius;
}

}  // namespace v_sekai
"

example : cppValidatorSource.length > 0 := by native_decide

end Fabric.Schema.SpringBoneRanges
