-- Copyright 2026 The openusd-fabric authors.
-- SPDX-License-Identifier: MIT
--
-- VRM humanoid bone enumeration + 0.x <-> 1.0 mapping (CHI-252).
--
-- The enum itself is stable between VRM 0.x and 1.0; the spec rename
-- happened in the structure that wraps it (`humanBones[]` -> keyed
-- `humanBones.<bone>`), not the names. This module enumerates all 55
-- bones the 1.0 spec defines, marks the subset that 1.0 requires (vs
-- optional), and exposes the identity 0.x <-> 1.0 map as the seam where
-- future divergence would land.

namespace Fabric.VrmUpgrade.HumanoidBones

/-- All 55 VRM 1.0 humanoid bones, in spec order. -/
def vrm1Bones : List String :=
  -- core (10)
  [ "hips", "spine", "chest", "upperChest", "neck", "head"
  , "leftEye", "rightEye", "jaw"
  -- legs (10)
  , "leftUpperLeg", "leftLowerLeg", "leftFoot", "leftToes"
  , "rightUpperLeg", "rightLowerLeg", "rightFoot", "rightToes"
  -- arms / shoulders (8)
  , "leftShoulder", "leftUpperArm", "leftLowerArm", "leftHand"
  , "rightShoulder", "rightUpperArm", "rightLowerArm", "rightHand"
  -- left fingers (15)
  , "leftThumbMetacarpal", "leftThumbProximal", "leftThumbDistal"
  , "leftIndexProximal", "leftIndexIntermediate", "leftIndexDistal"
  , "leftMiddleProximal", "leftMiddleIntermediate", "leftMiddleDistal"
  , "leftRingProximal", "leftRingIntermediate", "leftRingDistal"
  , "leftLittleProximal", "leftLittleIntermediate", "leftLittleDistal"
  -- right fingers (15)
  , "rightThumbMetacarpal", "rightThumbProximal", "rightThumbDistal"
  , "rightIndexProximal", "rightIndexIntermediate", "rightIndexDistal"
  , "rightMiddleProximal", "rightMiddleIntermediate", "rightMiddleDistal"
  , "rightRingProximal", "rightRingIntermediate", "rightRingDistal"
  , "rightLittleProximal", "rightLittleIntermediate", "rightLittleDistal"
  ]

/-- Bones VRM 1.0 marks as required (the rest are optional, e.g. fingers,
    chest, eyes, jaw, toes, shoulders). -/
def vrm1Required : List String :=
  [ "hips", "spine", "head"
  , "leftUpperLeg", "leftLowerLeg", "leftFoot"
  , "rightUpperLeg", "rightLowerLeg", "rightFoot"
  , "leftUpperArm", "leftLowerArm", "leftHand"
  , "rightUpperArm", "rightLowerArm", "rightHand"
  ]

/-- VRM 0.x bone identifier -> VRM 1.0. Today this is the identity. The
    function exists so any future spec divergence (a rename, a split,
    etc.) has a single named place to land. -/
def vrm0ToVrm1 (s : String) : Option String :=
  if vrm1Bones.contains s then some s else none

def vrm1ToVrm0 (s : String) : Option String :=
  if vrm1Bones.contains s then some s else none

example : vrm1Bones.length = 55 := by native_decide
example : vrm0ToVrm1 "hips" = some "hips" := by native_decide
example : vrm0ToVrm1 "notARealBone" = none := by native_decide
-- Every required bone is in the full enum.
example : vrm1Required.all vrm1Bones.contains := by native_decide

/-- JSON emission. Lists every bone, its VRM-0.x and 1.0 names (same
    string today), and whether 1.0 requires it. The Python + C# consumers
    parse this and use the `required` flag for validator messages. -/
def jsonSource : String :=
"{
  \"version\": 1,
  \"comment\": \"AUTO-GENERATED by lean/EmitArtifacts.lean from Fabric.VrmUpgrade.HumanoidBones. DO NOT EDIT.\",
  \"bones\": [
    { \"vrm0\": \"hips\",                     \"vrm1\": \"hips\",                     \"required\": true },
    { \"vrm0\": \"spine\",                    \"vrm1\": \"spine\",                    \"required\": true },
    { \"vrm0\": \"chest\",                    \"vrm1\": \"chest\",                    \"required\": false },
    { \"vrm0\": \"upperChest\",               \"vrm1\": \"upperChest\",               \"required\": false },
    { \"vrm0\": \"neck\",                     \"vrm1\": \"neck\",                     \"required\": false },
    { \"vrm0\": \"head\",                     \"vrm1\": \"head\",                     \"required\": true },
    { \"vrm0\": \"leftEye\",                  \"vrm1\": \"leftEye\",                  \"required\": false },
    { \"vrm0\": \"rightEye\",                 \"vrm1\": \"rightEye\",                 \"required\": false },
    { \"vrm0\": \"jaw\",                      \"vrm1\": \"jaw\",                      \"required\": false },
    { \"vrm0\": \"leftUpperLeg\",             \"vrm1\": \"leftUpperLeg\",             \"required\": true },
    { \"vrm0\": \"leftLowerLeg\",             \"vrm1\": \"leftLowerLeg\",             \"required\": true },
    { \"vrm0\": \"leftFoot\",                 \"vrm1\": \"leftFoot\",                 \"required\": true },
    { \"vrm0\": \"leftToes\",                 \"vrm1\": \"leftToes\",                 \"required\": false },
    { \"vrm0\": \"rightUpperLeg\",            \"vrm1\": \"rightUpperLeg\",            \"required\": true },
    { \"vrm0\": \"rightLowerLeg\",            \"vrm1\": \"rightLowerLeg\",            \"required\": true },
    { \"vrm0\": \"rightFoot\",                \"vrm1\": \"rightFoot\",                \"required\": true },
    { \"vrm0\": \"rightToes\",                \"vrm1\": \"rightToes\",                \"required\": false },
    { \"vrm0\": \"leftShoulder\",             \"vrm1\": \"leftShoulder\",             \"required\": false },
    { \"vrm0\": \"leftUpperArm\",             \"vrm1\": \"leftUpperArm\",             \"required\": true },
    { \"vrm0\": \"leftLowerArm\",             \"vrm1\": \"leftLowerArm\",             \"required\": true },
    { \"vrm0\": \"leftHand\",                 \"vrm1\": \"leftHand\",                 \"required\": true },
    { \"vrm0\": \"rightShoulder\",            \"vrm1\": \"rightShoulder\",            \"required\": false },
    { \"vrm0\": \"rightUpperArm\",            \"vrm1\": \"rightUpperArm\",            \"required\": true },
    { \"vrm0\": \"rightLowerArm\",            \"vrm1\": \"rightLowerArm\",            \"required\": true },
    { \"vrm0\": \"rightHand\",                \"vrm1\": \"rightHand\",                \"required\": true },
    { \"vrm0\": \"leftThumbMetacarpal\",      \"vrm1\": \"leftThumbMetacarpal\",      \"required\": false },
    { \"vrm0\": \"leftThumbProximal\",        \"vrm1\": \"leftThumbProximal\",        \"required\": false },
    { \"vrm0\": \"leftThumbDistal\",          \"vrm1\": \"leftThumbDistal\",          \"required\": false },
    { \"vrm0\": \"leftIndexProximal\",        \"vrm1\": \"leftIndexProximal\",        \"required\": false },
    { \"vrm0\": \"leftIndexIntermediate\",    \"vrm1\": \"leftIndexIntermediate\",    \"required\": false },
    { \"vrm0\": \"leftIndexDistal\",          \"vrm1\": \"leftIndexDistal\",          \"required\": false },
    { \"vrm0\": \"leftMiddleProximal\",       \"vrm1\": \"leftMiddleProximal\",       \"required\": false },
    { \"vrm0\": \"leftMiddleIntermediate\",   \"vrm1\": \"leftMiddleIntermediate\",   \"required\": false },
    { \"vrm0\": \"leftMiddleDistal\",         \"vrm1\": \"leftMiddleDistal\",         \"required\": false },
    { \"vrm0\": \"leftRingProximal\",         \"vrm1\": \"leftRingProximal\",         \"required\": false },
    { \"vrm0\": \"leftRingIntermediate\",     \"vrm1\": \"leftRingIntermediate\",     \"required\": false },
    { \"vrm0\": \"leftRingDistal\",           \"vrm1\": \"leftRingDistal\",           \"required\": false },
    { \"vrm0\": \"leftLittleProximal\",       \"vrm1\": \"leftLittleProximal\",       \"required\": false },
    { \"vrm0\": \"leftLittleIntermediate\",   \"vrm1\": \"leftLittleIntermediate\",   \"required\": false },
    { \"vrm0\": \"leftLittleDistal\",         \"vrm1\": \"leftLittleDistal\",         \"required\": false },
    { \"vrm0\": \"rightThumbMetacarpal\",     \"vrm1\": \"rightThumbMetacarpal\",     \"required\": false },
    { \"vrm0\": \"rightThumbProximal\",       \"vrm1\": \"rightThumbProximal\",       \"required\": false },
    { \"vrm0\": \"rightThumbDistal\",         \"vrm1\": \"rightThumbDistal\",         \"required\": false },
    { \"vrm0\": \"rightIndexProximal\",       \"vrm1\": \"rightIndexProximal\",       \"required\": false },
    { \"vrm0\": \"rightIndexIntermediate\",   \"vrm1\": \"rightIndexIntermediate\",   \"required\": false },
    { \"vrm0\": \"rightIndexDistal\",         \"vrm1\": \"rightIndexDistal\",         \"required\": false },
    { \"vrm0\": \"rightMiddleProximal\",      \"vrm1\": \"rightMiddleProximal\",      \"required\": false },
    { \"vrm0\": \"rightMiddleIntermediate\",  \"vrm1\": \"rightMiddleIntermediate\",  \"required\": false },
    { \"vrm0\": \"rightMiddleDistal\",        \"vrm1\": \"rightMiddleDistal\",        \"required\": false },
    { \"vrm0\": \"rightRingProximal\",        \"vrm1\": \"rightRingProximal\",        \"required\": false },
    { \"vrm0\": \"rightRingIntermediate\",    \"vrm1\": \"rightRingIntermediate\",    \"required\": false },
    { \"vrm0\": \"rightRingDistal\",          \"vrm1\": \"rightRingDistal\",          \"required\": false },
    { \"vrm0\": \"rightLittleProximal\",      \"vrm1\": \"rightLittleProximal\",      \"required\": false },
    { \"vrm0\": \"rightLittleIntermediate\",  \"vrm1\": \"rightLittleIntermediate\",  \"required\": false },
    { \"vrm0\": \"rightLittleDistal\",        \"vrm1\": \"rightLittleDistal\",        \"required\": false }
  ]
}
"

end Fabric.VrmUpgrade.HumanoidBones
