-- Copyright 2026 The openusd-fabric authors.
-- SPDX-License-Identifier: MIT
--
-- VRM 0.x -> 1.0 springbone field map (CHI-252).
--
-- The spec rename + range tightening table for per-joint springbone
-- parameters. VRM 0.x's `stiffinessForce` (typo preserved from the
-- original spec) becomes `stiffness` in 1.0; the rest of the field
-- names carry over but the legal ranges tighten.
--
-- Per the project convention, this Lean module is the source of truth;
-- the emitted maps/springbone_fields_map.json is what the Python loader
-- and the C# bridge consume.

namespace Fabric.VrmUpgrade.SpringBoneFields

structure FieldRename where
  vrm0       : String
  vrm1       : String
  lowerBound : Option Float  -- inclusive; `none` = unbounded
  upperBound : Option Float  -- inclusive; `none` = unbounded
  default    : Float
  deriving Repr

def renames : List FieldRename :=
  [ { vrm0 := "stiffinessForce", vrm1 := "stiffness"
    , lowerBound := some 0.0,    upperBound := some 4.0, default := 1.0 }
  , { vrm0 := "dragForce",       vrm1 := "dragForce"
    , lowerBound := some 0.0,    upperBound := some 1.0, default := 0.4 }
  , { vrm0 := "gravityPower",    vrm1 := "gravityPower"
    , lowerBound := some 0.0,    upperBound := none,     default := 0.0 }
  , { vrm0 := "hitRadius",       vrm1 := "hitRadius"
    , lowerBound := some 1e-6,   upperBound := none,     default := 0.02 }
  ]

/-- Clamp `v` to [lo, hi] when defined. -/
def clampF (v : Float) (lo : Option Float) (hi : Option Float) : Float :=
  let v := match lo with | some l => if v < l then l else v | none => v
  match hi with | some h => if v > h then h else v | none => v

-- Float lacks a kernel DecidableEq; use BEq + native_decide on the
-- Bool result to keep the proof pinning intent without needing a
-- custom DecidableEq instance.
example : (clampF 5.0 (some 0.0) (some 4.0) == 4.0) = true := by native_decide
example : (clampF (-1.0) (some 0.0) none == 0.0) = true := by native_decide
example : (clampF 0.0 (some 1e-6) none == 1e-6) = true := by native_decide

/-- JSON emission. Each entry is one field rename + clamp bounds. The
    Python and C# consumers iterate this and apply the named transform
    by entry. -/
def jsonSource : String :=
"{
  \"version\": 1,
  \"comment\": \"AUTO-GENERATED by lean/EmitArtifacts.lean from Fabric.VrmUpgrade.SpringBoneFields. DO NOT EDIT.\",
  \"fields\": [
    { \"vrm0\": \"stiffinessForce\", \"vrm1\": \"stiffness\",     \"min\": 0.0,      \"max\": 4.0,  \"default\": 1.0 },
    { \"vrm0\": \"dragForce\",       \"vrm1\": \"dragForce\",     \"min\": 0.0,      \"max\": 1.0,  \"default\": 0.4 },
    { \"vrm0\": \"gravityPower\",    \"vrm1\": \"gravityPower\",  \"min\": 0.0,      \"max\": null, \"default\": 0.0 },
    { \"vrm0\": \"hitRadius\",       \"vrm1\": \"hitRadius\",     \"min\": 1e-6,     \"max\": null, \"default\": 0.02 }
  ],
  \"notes\": [
    \"gravityDir (vector3) carries through unchanged — no clamp.\",
    \"center is a node reference; handled by the importer's bone resolver, not this table.\"
  ]
}
"

end Fabric.VrmUpgrade.SpringBoneFields
